name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        default: master

jobs:

  build-and-push-app:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
   
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pastvu/frontend:${{ github.event.inputs.tag }}
          build-args: |
            TAG=${{ github.event.inputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
